version: "3.5"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
    - npr_database
  environment: &base-app-environment
    NPR_DB_USER: sa
    NPR_DB_PASSWORD: "DevDev123!"
    NPR_DB_HOST: npr_database
    NPR_DB_PORT: 1433
    NPR_DB_NAME: master
    NPR_DB_TABLE_NAME: npr_table
  volumes:
    - ./src:/app/src
    - ./tests:/app/tests
    - ./jenkins-import:/app/jenkins-import
    - ./data:/data
  entrypoint: /app/jenkins-import/docker-entrypoint.sh

services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  npr_database:
    image: 'mcr.microsoft.com/mssql/server'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "DevDev123!"
      MSSQL_TCP_PORT: 1433

  dev:
    <<: *base-app
    build:
      context: .
      target: dev

  app:
    <<: *base-app
    image: docker-registry.data.amsterdam.nl/datapunt/parkeerrechten:${VERSION:-latest}
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-environment
      TMP_DATA_DIR: /tmp
